# Week of 2024-09-30 to 2024-10-07 (23)

### GHFirst (5)

- [Revert "Mark PyTorch module as no-gil valid and pythoncapi_compat.h (#136899)"](https://github.com/pytorch/pytorch/commit/9670e9e5b082c3fa88881bf3dba9d431a7689098)
  - Diff reverted internally ([comment](https://github.com/pytorch/pytorch/pull/136899#issuecomment-2392721534))
- [Revert "raw_alloc ignores PYTORCH_NO_CUDA_MEMORY_CACHING (#131114)"](https://github.com/pytorch/pytorch/commit/0d1701f310d8fd9fcd854b94e51e36b1bf61690d)
  - failing internal builds ([comment](https://github.com/pytorch/pytorch/pull/131114#issuecomment-2390615007))
- [Revert "[FSDP2] support torch._foreach_copy_(float8) for fully_shard(Float8Linear) (#135955)"](https://github.com/pytorch/pytorch/commit/2c9e194e23b02f0ed51b3d6bc0d9cf30924ba49a)
  - breaking internal tests ([comment](https://github.com/pytorch/pytorch/pull/135955#issuecomment-2389810936))
- [Revert "Init threadpool with user defined num_threads before default (#136793)"](https://github.com/pytorch/pytorch/commit/66e3186a486a1cb863aab8921a06a047916b4470)
  - Caused internal Oculus crash, and internal force landed a diff without exporting to GH =.= ([comment](https://github.com/pytorch/pytorch/pull/136793#issuecomment-2384148132))
- [Revert "Add int1 to int7 dtypes (#136301)"](https://github.com/pytorch/pytorch/commit/2ef1454189e6a3cc56da9f56917df1c710355ca3)
  - causing internal failures ([comment](https://github.com/pytorch/pytorch/pull/136301#issuecomment-2384119600))

### Ignored Signal (5)

- [Revert "[Distributed] Fix extra context on device 0 (#135273)"](https://github.com/pytorch/pytorch/commit/cd17b2645c9f63f2085cde2b12c44753809eb427)
  - Broken trunk distributed ci ([comment](https://github.com/pytorch/pytorch/pull/135273#issuecomment-2393772987))
- [Revert "Fix unlift to unblock training IR + run_decomp on aliasing constants (#137162)"](https://github.com/pytorch/pytorch/commit/525f6715bcb0506c02253451a838f5c33c6ca7d0)
  - Sorry for reverting your changes but many jobs are failing with NameError: name _recursive_getattr is not defined + a Lint job fails ([comment](https://github.com/pytorch/pytorch/pull/137162#issuecomment-2392036062))
- [Revert "Add py3.13t linux wheel build (#137127)"](https://github.com/pytorch/pytorch/commit/4559cddaf930a8f65f36cffd0ed8a264efad232c)
  - Sorry for reverting your changes but 2 jobs are failing ([comment](https://github.com/pytorch/pytorch/pull/137127#issuecomment-2389250791))
- [Revert "[dtensor][experimental] expose DTensor Context Parallel API (#137038)"](https://github.com/pytorch/pytorch/commit/b53ab8b86afdc1b3d3ee5ca57d09c4fe311e2476)
  - Sorry for reverting your changes but the doc build failure looks legit ([comment](https://github.com/pytorch/pytorch/pull/137038#issuecomment-2386902253))
- [Revert "Allow parallelize_module to get device_mesh from ambient context (#134247)"](https://github.com/pytorch/pytorch/commit/1ef5d4cddece720eaad8aa645d7eafab62d02c39)
  - Broke lint, which one can clearly see in PR CI https://github.com/pytorch/pytorch/actions/runs/11112138513/job/30873604386  ([comment](https://github.com/pytorch/pytorch/pull/134247#issuecomment-2383952449))

### Not through pytorchbot (1)

- [Revert runtime numeric check in inductor due to increased compilation time (#137324)](https://github.com/pytorch/pytorch/commit/0eba7e5451ac53c3e75be258236f3a11acaf2c1c)

### No Signal (10)

- [Revert "Add meta functions for `lerp`, `addcmul`, and `addcdiv`. (#136909)"](https://github.com/pytorch/pytorch/commit/f56f7476d3090506577dba6e1c03d92b376e9078)
  - breaks trunk jobs ([comment](https://github.com/pytorch/pytorch/pull/136909#issuecomment-2393774694))
- [Revert "[PyTorch] Port ExecuTorch bfdot improvement back to ATen BlasKernel (#136331)"](https://github.com/pytorch/pytorch/commit/5509207543a393210a1dae4eefbd987714a91c6c)
  - Breaks aarch64 builds, see link below ([comment](https://github.com/pytorch/pytorch/pull/136331#issuecomment-2393760135))
- [Revert "Skip kernel saving if already existed. (#136389)"](https://github.com/pytorch/pytorch/commit/86b715c5f6d02383da52266757b937acbf7a176c)
  - Issue #136940  ([comment](https://github.com/pytorch/pytorch/pull/136389#issuecomment-2386950623))
- [Revert "inductor: use previous guards to know if a size is 1 for broadcasting (#136670)"](https://github.com/pytorch/pytorch/commit/696d01aef3ea6841a5f51aa7c9c21ad1f4874382)
  - Something in this stack seems to be causing tests to fail on trunk. See functorch/test_control_flow.py::TestControlFlow::test_associative_scan_dim_reverse_True_combine_mode_generic_cuda [GH job link](https://github.com/pytorch/pytorch/actions/runs/11107079955/job/30872132411) [HUD commit link](https://hud.pytorch.org/pytorch/pytorch/commit/c010c6099bf304bbb681af534b9f3996c33ce582) ([comment](https://github.com/pytorch/pytorch/pull/136670#issuecomment-2386303362))
- [Revert "compile time benchmarks for AOTDispatcher (inference/training/subclasses) (#136759)"](https://github.com/pytorch/pytorch/commit/951107e8c21eeb1984c125be629bae11f6264bb4)
  - Something in this stack seems to be causing tests to fail on trunk. See functorch/test_control_flow.py::TestControlFlow::test_associative_scan_dim_reverse_True_combine_mode_generic_cuda [GH job link](https://github.com/pytorch/pytorch/actions/runs/11107079955/job/30872132411) [HUD commit link](https://hud.pytorch.org/pytorch/pytorch/commit/c010c6099bf304bbb681af534b9f3996c33ce582) ([comment](https://github.com/pytorch/pytorch/pull/136670#issuecomment-2386303362))
- [Revert "compile time benchmarks for AOTDispatcher (partitioner) (#136760)"](https://github.com/pytorch/pytorch/commit/923410193b3e2720780cd4694f7656fb8e33899d)
  - Something in this stack seems to be causing tests to fail on trunk. See functorch/test_control_flow.py::TestControlFlow::test_associative_scan_dim_reverse_True_combine_mode_generic_cuda [GH job link](https://github.com/pytorch/pytorch/actions/runs/11107079955/job/30872132411) [HUD commit link](https://hud.pytorch.org/pytorch/pytorch/commit/c010c6099bf304bbb681af534b9f3996c33ce582) ([comment](https://github.com/pytorch/pytorch/pull/136670#issuecomment-2386303362))
- [Revert "Simplify find_localzeros (#133325)"](https://github.com/pytorch/pytorch/commit/7303716005a6a174a45ff01f78a399607a413451)
  - https://fb.workplace.com/groups/gpuinference/permalink/2921405651341417/ ([comment](https://github.com/pytorch/pytorch/pull/133325#issuecomment-2385832600))
- [Revert "Don't uselessly recompute axiom dict every static eval call (#135429)"](https://github.com/pytorch/pytorch/commit/af64c44b56e3e9f31d7460e904da845ca8dea9f6)
  - try again ([comment](https://github.com/pytorch/pytorch/pull/135429#issuecomment-2384288879))
- [Revert "Turn on type-checking in torch.fx.experimental.symbolic_shapes (#136972)"](https://github.com/pytorch/pytorch/commit/8982906502153bc1495e5fc0e254578da6836ff2)
  - need to back out for merge conflict ([comment](https://github.com/pytorch/pytorch/pull/136972#issuecomment-2384182244))
- [Revert "[Inductor] Pick ISA for inductor based on ATEN_CPU_CAPABILITY (#123514)"](https://github.com/pytorch/pytorch/commit/c13c7e11c553b2a848c158c8e2a5e20bbd5d7f1c)
  - Sorry for reverting your change but its test_cpu_repro test is failing in trunk https://hud.pytorch.org/pytorch/pytorch/commit/6931c1644afdba53e63ce5671455e4e1b7265dd9 ([comment](https://github.com/pytorch/pytorch/pull/123514#issuecomment-2383563919))

### Weird (2)

- [Revert "Format torch.fx.experimental.symbolic_shapes with PYFMT (#136934)"](https://github.com/pytorch/pytorch/commit/66a269afe87ce331cdf06d08d63c466f9205532e)
  - merge conflict revert ([comment](https://github.com/pytorch/pytorch/pull/136934#issuecomment-2384195881))
- [Revert "Format torch.fx.experimental.validator (#136935)"](https://github.com/pytorch/pytorch/commit/c94536ae74a4dc4fa2587a82f30387d687cf9c33)
  - merge conflict revert ([comment](https://github.com/pytorch/pytorch/pull/136934#issuecomment-2384195881))
